language: java
jdk: oraclejdk8
script: mvn clean verify -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn  --batch-mode -fae -Dmaven.test.failure.ignore=true  -f releng/com.yakindu.solidity.releng/pom.xml 
