sudo: false
language: java
dist: precise
jdk: 
 - oraclejdk8
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - DISPLAY=:99.0
before_install:
- sh -e /etc/init.d/xvfb start - sleep 10
script:
- cd releng/com.yakindu.solidity.releng
- mvn clean verify -P!tests
