title: YAKINDU Solidity Tools
description: The free to use, open source YAKINDU Solidity Tools provide an integrated development environment for Ethereum / Solidity based smart contracts.
twitter_username: yakindu
theme: jekyll-theme-slate
